import img1 from './assets/image/img1.jpg';
import img2 from './assets/image/img2.jpg';
import img3 from './assets/image/img3.jpg';
import img4 from './assets/image/img4.jpg';
import img5 from './assets/image/img5.jpg';
import img6 from './assets/image/img6.jpg';
import img7 from './assets/image/img7.jpg';
import img8 from './assets/image/img8.jpg';

const properties = [
  {
    id: 1,
    areaImage: img1,
    areaImage2: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1500,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 2,
    areaImage: img2,
    areaImage2: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1200,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 3,
    areaImage: img3,
    areaImage2: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1400,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 4,
    areaImage: img4,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 70,
      doubleRoom: 110,
      threeRoom: 160,
    },
    area: 1000,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 5,
    areaImage: img5,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 120,
      doubleRoom: 170,
      threeRoom: 220,
    },
    area: 1600,
    totalBeds: 4,
    bath: 3,
    garage: true,
  },
  {
    id: 6,
    areaImage: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 95,
      doubleRoom: 145,
      threeRoom: 190,
    },
    area: 1300,
    totalBeds: 3,
    bath: 2,
    garage: false,
  },
  {
    id: 7,
    areaImage: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 85,
      doubleRoom: 130,
      threeRoom: 175,
    },
    area: 1100,
    totalBeds: 2,
    bath: 1,
    garage: true,
  },
  {
    id: 8,
    areaImage: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 75,
      doubleRoom: 120,
      threeRoom: 165,
    },
    area: 900,
    totalBeds: 1,
    bath: 1,
    garage: false,
  },
  // Duplicate the existing products and update their IDs
  {
    id: 9,
    areaImage: img1,
    areaImage2: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1500,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 10,
    areaImage: img2,
    areaImage2: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1200,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 11,
    areaImage: img3,
    areaImage2: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1400,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 12,
    areaImage: img4,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 70,
      doubleRoom: 110,
      threeRoom: 160,
    },
    area: 1000,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 13,
    areaImage: img5,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 120,
      doubleRoom: 170,
      threeRoom: 220,
    },
    area: 1600,
    totalBeds: 4,
    bath: 3,
    garage: true,
  },
  {
    id: 14,
    areaImage: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 95,
      doubleRoom: 145,
      threeRoom: 190,
    },
    area: 1300,
    totalBeds: 3,
    bath: 2,
    garage: false,
  },
  {
    id: 15,
    areaImage: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 85,
      doubleRoom: 130,
      threeRoom: 175,
    },
    area: 1100,
    totalBeds: 2,
    bath: 1,
    garage: true,
  },
  {
    id: 16,
    areaImage: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 75,
      doubleRoom: 120,
      threeRoom: 165,
    },
    area: 900,
    totalBeds: 1,
    bath: 1,
    garage: false,
  },
  // Duplicate the existing products again and update their IDs
  {
    id: 17,
    areaImage: img1,
    areaImage2: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1500,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 18,
    areaImage: img2,
    areaImage2: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1200,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 19,
    areaImage: img3,
    areaImage2: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1400,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 20,
    areaImage: img4,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 70,
      doubleRoom: 110,
      threeRoom: 160,
    },
    area: 1000,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 21,
    areaImage: img5,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 120,
      doubleRoom: 170,
      threeRoom: 220,
    },
    area: 1600,
    totalBeds: 4,
    bath: 3,
    garage: true,
  },
  {
    id: 22,
    areaImage: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 95,
      doubleRoom: 145,
      threeRoom: 190,
    },
    area: 1300,
    totalBeds: 3,
    bath: 2,
    garage: false,
  },
  {
    id: 23,
    areaImage: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 85,
      doubleRoom: 130,
      threeRoom: 175,
    },
    area: 1100,
    totalBeds: 2,
    bath: 1,
    garage: true,
  },
  {
    id: 24,
    areaImage: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 75,
      doubleRoom: 120,
      threeRoom: 165,
    },
    area: 900,
    totalBeds: 1,
    bath: 1,
    garage: false,
  },
  // Duplicate the existing products once more and update their IDs
  {
    id: 25,
    areaImage: img1,
    areaImage2: img8,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1500,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 26,
    areaImage: img2,
    areaImage2: img7,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1200,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 27,
    areaImage: img3,
    areaImage2: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 19000,
      doubleRoom: 10000,
      threeRoom: 7000,
    },
    area: 1400,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 28,
    areaImage: img4,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 70,
      doubleRoom: 110,
      threeRoom: 160,
    },
    area: 1000,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 29,
    areaImage: img5,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 120,
      doubleRoom: 170,
      threeRoom: 220,
    },
    area: 1600,
    totalBeds: 4,
    bath: 3,
    garage: true,
  },
  {
    id: 30,
    areaImage: img6,
    name: 'Sky Dandelions Apartment',
    location: 'Sector-23, Gurugram',
    roomPrices: {
      singleRoom: 95,
      doubleRoom: 145,
      threeRoom: 190,
    },
    area: 1300,
    totalBeds: 3,
    bath: 2,
    garage: false,
  },
];

export default properties;
