const properties = [
  {
    id: 1,
    areaImage: "./assets/image/img2.jpg",
    name: "Property 1",
    location: "Location 1",
    roomPrices: {
      singleRoom: 100,
      doubleRoom: 150,
      threeRoom: 200,
    },
    area: 1500,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  {
    id: 2,
    areaImage: "./assets/image/img3.jpg",
    name: "Property 2",
    location: "Location 2",
    roomPrices: {
      singleRoom: 80,
      doubleRoom: 120,
      threeRoom: 180,
    },
    area: 1200,
    totalBeds: 2,
    bath: 1,
    garage: false,
  },
  {
    id: 3,
    areaImage: "./assets/image/img4.jpg",
    name: "Property 3",
    location: "Location 3",
    roomPrices: {
      singleRoom: 90,
      doubleRoom: 140,
      threeRoom: 190,
    },
    area: 1400,
    totalBeds: 3,
    bath: 2,
    garage: true,
  },
  // {
  //   id: 4,
  //   areaImage: "./assets/image/img5.jpg",
  //   name: "Property 4",
  //   location: "Location 4",
  //   roomPrices: {
  //     singleRoom: 70,
  //     doubleRoom: 110,
  //     threeRoom: 160,
  //   },
  //   area: 1000,
  //   totalBeds: 2,
  //   bath: 1,
  //   garage: false,
  // },
  // {
  //   id: 5,
  //   areaImage: "./assets/image/img6.jpg",
  //   name: "Property 5",
  //   location: "Location 5",
  //   roomPrices: {
  //     singleRoom: 120,
  //     doubleRoom: 170,
  //     threeRoom: 220,
  //   },
  //   area: 1600,
  //   totalBeds: 4,
  //   bath: 3,
  //   garage: true,
  // },
  // {
  //   id: 6,
  //   areaImage: "./src/assets/image/img6.jpg",
  //   name: "Property 6",
  //   location: "Location 6",
  //   roomPrices: {
  //     singleRoom: 95,
  //     doubleRoom: 145,
  //     threeRoom: 190,
  //   },
  //   area: 1300,
  //   totalBeds: 3,
  //   bath: 2,
  //   garage: false,
  // },
  // {
  //   id: 7,
  //   areaImage: "./src/assets/image/img7.jpg",
  //   name: "Property 7",
  //   location: "Location 7",
  //   roomPrices: {
  //     singleRoom: 85,
  //     doubleRoom: 130,
  //     threeRoom: 175,
  //   },
  //   area: 1100,
  //   totalBeds: 2,
  //   bath: 1,
  //   garage: true,
  // },
  // {
  //   id: 8,
  //   areaImage: "./assets/image/img8.jpg",
  //   name: "Property 8",
  //   location: "Location 8",
  //   roomPrices: {
  //     singleRoom: 75,
  //     doubleRoom: 120,
  //     threeRoom: 165,
  //   },
  //   area: 900,
  //   totalBeds: 1,
  //   bath: 1,
  //   garage: false,
  // },
];
export default properties;
